version: '3'

services:
  api:
    build:
      context: ./backend
      args: {}
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
