version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: blueprinthq
      POSTGRES_PASSWORD: blueprinthq
      POSTGRES_DB: blueprinthq
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    depends_on:
      - db
  
  app:
    build:
      context: ./frontend
    command: yarn start
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/code
    depends_on:
      - api

volumes:
  data: {}
