# Generated by Django 3.0.8 on 2020-07-14 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['section_id', 'value']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['section_id', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('section_id', 'value')},
        ),
    ]
